- name: Install generic dependencies on development VM
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - createrepo
    - tree
    - lynx
    - docker-python
  become: yes
  become_user: root

